apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluxai-cloudflare
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: NODE_SELECTOR
      containers:
      - name: edge6-4090-8080
        image: ghcr.io/huggingface/text-generation-inference:2.0.4
      - name: cloudflared
        args:
        - --token
        - CLOUDFLARE_TOKEN
