apiVersion: v1
kind: Service
metadata:
  name: fluxai-cloudflare-service
spec:
  type: NodePort
  selector:
    app: fluxai-cloudflare
  ports:
  - protocol: TCP
    port: 8080 # Port on the service
    targetPort: 8080 # Port on the pods
