apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluxai-cloudflare
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: "78fea1345f"
      containers:
      - name: edge1-4090-8080
        image: ghcr.io/huggingface/text-generation-inference:2.0.4
      - name: cloudflared
        args:
        - --token
        - eyJhIjoiOThkNGMzYzRkZWNmMzc5ZGM0YTE4NjU0YThhYjZjYmYiLCJ0IjoiOWFlZjZjNWEtNDk0Ny00YjY5LTk5ZmUtZDNmNmRmZDNiZTlmIiwicyI6Ik1Ua3pNRFk0WlRFdFl6RXlOQzAwTWpOaExXRTBaVEl0WkdNeFpqWTFZVFF6WlRZMyJ9
