apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluxai-cloudflare
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: "04cd662d67"
      containers:
      - name: edge-4090-8080
        image: ghcr.io/huggingface/text-generation-inference:2.2.0
        args: ["--env"]
        resources:
         limits:
            nvidia.com/gpu: 1 # Allocate 1 GPU
        env:
        - name: MODEL_ID
          value: "cognitivecomputations/dolphin-2.9.4-llama3.1-8b"
        - name: SHARDED
          value: "false"
        - name: LOG_LEVEL
          value: "INFO"
        - name: HF_HUB_ENABLE_HF_TRANSFER
          value: "0"
        - name: TRUST_REMOTE_CODE
          value: "true"
        - name: PORT
          value: "8080"
        - name: MAX_INPUT_TOKENS
          value: "4000"
        - name: MAX_TOTAL_TOKENS
          value: "5000"
      - name: cloudflared
        args:
        - --token
        - eyJhIjoiOThkNGMzYzRkZWNmMzc5ZGM0YTE4NjU0YThhYjZjYmYiLCJ0IjoiNWNlMTRkZmItMmQ0ZC00MzMwLWI0YzItMDNiNmQwMzZiNjMxIiwicyI6IlptTm1NVEEzWlRZdE56TTBaUzAwTURFekxXSTFNamN0WVRSbU1UZGxNakJoTkRrNSJ9
