apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluxai-cloudflare
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: "a7f6db9b57"
      containers:
      - name: edge1-4090-8080
        image: ghcr.io/huggingface/text-generation-inference:2.0.4
      - name: cloudflared
        args:
        - --token
        - eyJhIjoiOThkNGMzYzRkZWNmMzc5ZGM0YTE4NjU0YThhYjZjYmYiLCJ0IjoiODk2MGZjNGQtNzU1Ni00ZTM4LWIwNGQtZTNkMDY4MGE4MWIwIiwicyI6IlpqZG1PV1V6TldZdE5tTTRZaTAwTVRFeExXSm1abVl0T1RSa01XUXpOR0V5TW1GbSJ9
