apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluxai-cloudflare
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: "3a5455f041"
      containers:
      - name: fluxai8080
        image: ghcr.io/huggingface/text-generation-inference:2.1.0
        resources:
          limits:
            nvidia.com/gpu: 1
      - name: cloudflared
        args:
        - cloudflared
        - tunnel
        - --metrics
        - 0.0.0.0:2000
        - run
        - --token
        - new-token-value 
